/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Usuario' at '2/08/16 12:48' with Gradle 2.14
 *
 * @author Usuario, @date 2/08/16 12:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
